server:
    port: 8089
spring:
    application:
        name: Spring Kotlin Spatial
    datasource:
        url: jdbc:postgresql://${SERVER_IP:localhost}:${POSTGRESQL_PORT:54321}/${POSTGRESQL_DB:boilerplate}?currentSchema=${POSTGRESQL_SCHEMA:public}
        username: ${POSTGRESQL_USER:postgres}
        password: ${POSTGRESQL_PASSWORD:senocak}
        hikari:
            minimum-idle: 1 # The minimum connection pool size is 1
            maximum-pool-size: 40 # it can grow to at most 40 connections
            max-lifetime: 900_000 # to retire pooled connections after 10 minutes
            transaction-isolation: TRANSACTION_READ_COMMITTED # to optimize the number of gap locks held by db when traversing the clustered index for bulk updates or deletes.
            pool-name: SpringKotlinSpatialHikariCP
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
        hibernate:
            ddl-auto: validate
        show-sql: false
    data:
        jdbc:
            dialect: postgresql
        redis:
            HOST: ${REDIS_HOST:localhost}
            PORT: ${REDIS_PORT:6379}
            PASSWORD: ${REDIS_PASSWORD:}
            TIMEOUT: ${REDIS_TIMEOUT:300}
        mongodb:
            host: ${SERVER_IP:localhost}
            port: ${MONGO_PORT:27017}
            username: ${MONGO_USER:anil}
            database: ${MONGO_DB:boilerplate}
            password: ${MONGO_PASSWORD:senocak}
            authentication-database: admin
            auto-index-creation: true
            connection-pool:
                max-size: 100
                min-size: 5
            socket:
                connect-timeout: 5000
                read-timeout: 5000
logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
        com:
            github:
                senocak:
                    sks:
                        mongo: INFO
