spring:
    sql:
        init:
            mode: always
    application:
        name: Spring Kotlin Spatial
    datasource:
        url: jdbc:postgresql://${SERVER_IP:localhost}:${POSTGRESQL_PORT:54321}/${POSTGRESQL_DB:boilerplate}?currentSchema=${POSTGRESQL_SCHEMA:public}
        username: ${POSTGRESQL_USER:postgres}
        password: ${POSTGRESQL_PASSWORD:senocak}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
        hibernate:
            ddl-auto: update
        show-sql: false
    data:
        jdbc:
            dialect: postgresql
logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace