### All cities
GET http://localhost:8089/api/v1/mongo/cities

> {%
    client.global.set("firstCityId", response.body[0].id)
%}

### findNearestCities by city id
GET http://localhost:8089/api/v1/mongo/city/{{firstCityId}}/70

### findNearestCities by lat and lng
GET http://localhost:8089/api/v1/mongo/city/39.9208/32.8541/84000

### All districts
GET http://localhost:8089/api/v1/mongo/district

> {%
    client.global.set("firstDistrictId", response.body[0].id)
%}

### findNearestDistricts by district id
GET http://localhost:8089/api/v1/mongo/district/{{firstDistrictId}}/40

### findNearestDistricts by lat and lng
GET http://localhost:8089/api/v1/mongo/district/39.9208/32.8541/4000
