### getAllCities
GET http://localhost:8089/api/v1/postgis/cities

> {%
    client.global.set("firstCityId", response.body[0].id)
%}

### findNearestCities
GET http://localhost:8089/api/v1/postgis/city/{{firstCityId}}/70000

### findNearestCitiesByCityId
GET http://localhost:8089/api/v1/postgis/city/39.9208/32.8541/70000

### getAllDistricts
GET http://localhost:8089/api/v1/postgis/districts

> {%
    client.global.set("firstDistrictId", response.body[0].id)
%}

### findNearestDistricts
GET http://localhost:8089/api/v1/postgis/district/{{firstDistrictId}}/40000

### findNearestDistrictsByDistrictId
GET http://localhost:8089/api/v1/postgis/district/39.9208/32.8541/4000

